name: build-test-release-deploy

on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - run: |
          chmod +x mvnw 
          ./mvnw clean verify
      - uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/app.jar
          retention-days: 1

  terraform-check:
    runs-on: ubuntu-latest
    environment: oskar-westmeijer-environment
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_INFRA_SERVICE_ACCOUNT }}
      - name: Terraform Format
        run: terraform fmt -recursive -check
      - name: Terraform Validate
        run: terraform validate

  codeql-check:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  trivy-image-check:
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    environment: oskar-westmeijer-environment
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target
      - name: build image
        run: |
          docker build -t '${{ secrets.DOCKER_USERNAME }}/gcp-spring-boot-sample:sha-${{ github.sha }} .
      - name: trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/gcp-spring-boot-sample:sha-${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          ignore-unfixed: true
      - name: upload trivy image scan results to GitHub security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'

  dependabot-automerge:
    needs: [ build-and-test, terraform-check, codeql-check ]
    runs-on: ubuntu-latest
    environment: oskar-westmeijer-environment
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release-docker-image:
    needs: [ build-and-test, terraform-check, codeql-check ]
    runs-on: ubuntu-latest
    environment: oskar-westmeijer-environment
    if: github.ref == 'refs/heads/main'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target
      - name: image tagging
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/gcp-spring-boot-sample
          tags: |
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,format=long
      - name: build image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy-to-gcp:
    needs: [ release-docker-image ]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-to-gcp.yml
    with:
      commit-sha: ${{ github.sha }}
    secrets: inherit

