name: main-build-test-release

on:
  push:
    branches:
      - main
jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - run: ./mvnw clean verify
      - uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/app.jar
          retention-days: 1

  release-backend-docker-image:
    needs: [ backend-build-and-test]
    runs-on: ubuntu-latest
    environment: oskar-westmeijer-environment
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target
      - name: image tagging
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: oskarwestmeijer/gcp-spring-boot-sample
          tags: |
            # full length sha
            type=sha,format=long
      - name: build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
